export const keys = {
  me: ['auth', 'me'] as const,
  dashboard: ['dashboard'] as const,
  broadcast: ['broadcast', 'active'] as const,
  songs: ['songs', 'list'] as const,
  song: (id: string | number) => ['songs', 'detail', String(id)] as const,
  prayer: ['prayer', 'cycle'] as const,
  prayerMembers: ['prayer', 'members'] as const,
  events: ['events', 'list'] as const,
  sundayServices: (from: string, to: string) => ['calendar', 'sunday-services', from, to] as const,
  feedUnread: ['feed', 'unread-count'] as const,
  eventOccurrenceOverrides: ['events', 'occurrence-overrides'] as const,
  schedule: ['schedule'] as const,
  adminUsers: ['admin', 'users'] as const,
  adminUser: (id: string | number) => ['admin', 'users', String(id)] as const,
  logs: ['admin', 'logs'] as const,
  sections: ['admin', 'sections'] as const,
  notifications: ['notifications', 'settings'] as const,
  sectionVisibility: ['settings', 'sections', 'visibility'] as const,
  rolePermissions: ['admin', 'role-permissions'] as const,
  rolePermissionsPublic: ['settings', 'role-permissions', 'public'] as const,
  calendarDay: (dateKey: string) => ['calendar', 'day', dateKey] as const,
  dashboardNotes: (dateKey: string) => ['calendar', 'dashboard-coordinator-notes', dateKey] as const,
  broadcastArchive: (limit: number) => ['broadcast', 'archive', limit] as const,
  sermonNotes: ['sermon-notes', 'list'] as const,
  sermonNote: (id: string | number) => ['sermon-notes', 'detail', String(id)] as const,
} as const;

