CREATE TABLE IF NOT EXISTS public.mentor_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_id INTEGER NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  curator_id INTEGER NOT NULL REFERENCES public.members(id) ON DELETE RESTRICT,
  week_number INTEGER NOT NULL CHECK (week_number BETWEEN 1 AND 53),
  year INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 3000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT mentor_assignments_unique_week UNIQUE (participant_id, week_number, year)
);

CREATE INDEX IF NOT EXISTS mentor_assignments_participant_week_idx
  ON public.mentor_assignments (participant_id, year DESC, week_number DESC);

CREATE INDEX IF NOT EXISTS mentor_assignments_curator_week_idx
  ON public.mentor_assignments (curator_id, year DESC, week_number DESC);
